// tipagem da prioridade gut gravidade
const profileType = ["ADMIN", "COBRADOR"] as const;

export type ProfileType = (typeof profileType)[number];

export const appRoutes = [
  {
    title: "Home",
    to: "/home-admin",
    icon: "mdi-home-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 1,
  },
  {
    title: "Home",
    to: "/home-lawyer",
    icon: "mdi-home-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO"],
    order: 1,
  },
  {
    title: "Home",
    to: "/home-medic",
    icon: "mdi-home-outline",
    visible: true,
    isMenu: true,
    profiles: ["MEDICO"],
    order: 1,
  },
  {
    title: "Solicitações",
    to: "/solicitations",
    icon: "mdi-file-document-edit-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO", "ADMIN"],
    order: 2,
  },
  {
    title: "Advogados",
    to: "/lawyer",
    icon: "mdi-account-tie-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 3,
  },
  {
    title: "Médicos parceiros",
    to: "/medics",
    icon: "mdi-stethoscope",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 4,
  },
  {
    title: "Pacientes",
    to: "/patient",
    icon: "mdi-account-multiple-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN", "ADVOGADO", "MEDICO"],
    order: 5,
  },
  {
    title: "Agendamentos",
    to: "/schedules",
    icon: "mdi-calendar-clock-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 6,
  },
  {
    title: "Consultas",
    to: "/queries",
    icon: "mdi-hospital-box-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN", "ADVOGADO", "MEDICO"],
    order: 7,
  },
  {
    title: "Consultas agendadas",
    to: "/scheduled-queries",
    icon: "mdi-hospital-box-outline",
    visible: true,
    isMenu: true,
    profiles: ["MEDICO"],
    order: 8,
  },
  {
    title: "Pacotes de Serviços",
    to: "/packages",
    icon: "mdi-package-variant-closed",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 9,
  },
  {
    title: "Administradores",
    to: "/admins",
    icon: "mdi-account-multiple-check-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 10,
  },
  {
    title: "Perfil",
    to: "/profile",
    icon: "mdi-account-multiple-check-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN", "MEDICO", "ADVOGADO"],
    order: -1,
  },
  {
    title: "Estatísticas",
    to: "/estatistics",
    icon: "mdi-chart-bell-curve-cumulative",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO"],
    order: 11,
  },
  {
    title: "Meu financeiro",
    to: "/my-financial",
    icon: "mdi-chart-box-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 12,
  },
  {
    title: "Relatório de vendas",
    to: "/report-sales",
    icon: "mdi-file-chart-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 13,
  },
];
