export const addressCategoryType = {
  patient: "PATIENT",
  medic: "MEDIC",
  lawyer: "LAWYER",
  admin: "ADMIN",
  user: "USER",
};

export const filesCategoryType = {
  patient: "PATIENT",
  medic: "MEDIC",
  lawyer: "LAWYER",
  userAvatar: "USER_AVATAR",
  query: "QUERY",
};

export const userCategoryType = {
  query20: {
    type: "QUERY20",
    description: "Pacote completo de serviços com 20 consultas",
  },
  query30: {
    type: "QUERY30",
    description: "Pacote completo de serviços com 30 consultas",
  },
  query40: {
    type: "QUERY40",
    description: "Pacote completo de serviços com 40 consultas",
  },
  query50: {
    type: "QUERY50",
    description: "Pacote completo de serviços com 50 consultas",
  },
};

export const solicitationStates = [
  {
    name: "Pendente",
    value: "open",
  },
  {
    name: "Agendada",
    value: "scheduled",
  },
  {
    name: "Concluída",
    value: "closed",
  },
  {
    name: "Cancelada",
    value: "canceled",
  },
  {
    name: "Em andamento",
    value: "in_progress",
  },
];

export const appRoutes = [
  {
    title: "Início",
    to: "/admin/home",
    icon: "mdi-home-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 1,
  },
  {
    title: "Início",
    to: "/lawyer/home",
    icon: "mdi-home-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO"],
    order: 2,
  },
  {
    title: "Início",
    to: "/medic/home",
    icon: "mdi-home-outline",
    visible: true,
    isMenu: true,
    profiles: ["MEDICO"],
    order: 3,
  },
  {
    title: "Solicitações",
    to: "/solicitations",
    icon: "mdi-file-document-edit-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO", "ADMIN"],
    order: 4,
  },
  {
    title: "Advogados",
    to: "/admin/lawyers",
    icon: "mdi-account-tie-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 5,
  },
  {
    title: "Pacientes",
    to: "/patient",
    icon: "mdi-clipboard-account-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN", "ADVOGADO"],
    order: 6,
  },
  {
    title: "Agendamentos",
    to: "/schedules",
    icon: "mdi-calendar-clock-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN", "MEDICO"],
    order: 7,
  },
  {
    title: "Administração",
    to: "/admin/administration",
    icon: "mdi-shield-account-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 8,
  },
  {
    title: "Dashboard de vendas",
    to: "/admin/dashobard-sales",
    icon: "mdi-cart-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADMIN"],
    order: 9,
  },
  {
    title: "Estatísticas",
    to: "/lawyer/estatistics",
    icon: "mdi-view-dashboard-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO"],
    order: 10,
  },
  {
    title: "Meus Saldos",
    to: "/lawyer/my-salts",
    icon: "mdi-chart-line-variant",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO"],
    order: 11,
  },
  {
    title: "Indicações",
    to: "/lawyer/my-indications",
    icon: "mdi-account-network-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO"],
    order: 12,
  },
  {
    title: "Vídeos/Tutoriais",
    to: "/videos",
    icon: "mdi-folder-play-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO", "ADMIN", "MEDICO"],
    order: 13,
  },
  {
    title: "Minha conta",
    to: "/lawyer/my-account",
    icon: "mdi-card-account-details-outline",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO"],
    order: 14,
  },
  {
    title: "Pacotes de Serviços",
    to: "/services-packages",
    icon: "mdi-cart-arrow-up",
    visible: true,
    isMenu: true,
    profiles: ["ADVOGADO", "ADMIN"],
    order: 15,
  },
  {
    title: "Laudos  Médicos",
    to: "/medical-report",
    icon: "mdi-hospital-box-outline",
    visible: true,
    isMenu: true,
    profiles: ["MEDICO", "ADMIN"],
    order: 16,
  },
  {
    title: "Minha Conta",
    to: "/medic/my-account",
    icon: "mdi-card-account-details-outline",
    visible: true,
    isMenu: true,
    profiles: ["MEDICO"],
    order: 17,
  },

  // Rotas que não serão apresentadas no menu
  {
    title: "Nova solicitação",
    to: "/solicitations/new",
    icon: "mdi-file-document-edit-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADVOGADO", "ADMIN"],
    order: -1,
  },
  {
    title: "Editar solicitação",
    to: "/solicitations/edit",
    icon: "mdi-file-document-edit-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADVOGADO", "ADMIN"],
    order: -1,
  },
  {
    title: "Consultas",
    to: "/admin/queries",
    icon: "mdi-hospital-box-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN"],
    order: -1,
  },
  {
    title: "Relatório de vendas",
    to: "/admin/report-sales",
    icon: "mdi-file-chart-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN"],
    order: -1,
  },
  {
    title: "Perfil",
    to: "/profile",
    icon: "mdi-account-multiple-check-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN", "MEDICO"],
    order: -1,
  },
  {
    title: "Médicos parceiros",
    to: "/admin/medics",
    icon: "mdi-stethoscope",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN"],
    order: -1,
  },
  {
    title: "Pacotes de Serviços",
    to: "/admin/packages",
    icon: "mdi-package-variant-closed",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN"],
    order: -1,
  },
  {
    title: "Cadastro de modelo de laudo",
    to: "/admin/report-models",
    icon: "mdi-account-multiple-check-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN"],
    order: -1,
  },
  {
    title: "Administradores do sistema",
    to: "/admin/admins",
    icon: "mdi-account-multiple-check-outline",
    visible: true,
    isMenu: false,
    profiles: ["ADMIN"],
    order: -1,
  },
];
