import './api-routes/auth.js'
import './api-routes/address.js'
import './api-routes/dashboard_admin_sales.js'
import './api-routes/asaas.js'
import './api-routes/consultation.js'
import './api-routes/file.js'
import './api-routes/medic.js'
