import vine from '@vinejs/vine'

export const fileStoreValidator = vine.compile(
  vine.object({
    file: vine.file({
      size: '500mb',
      extnames: [
        'jpg',
        'jpeg',
        'png',
        'png',
        'webp',
        'pdf',
        'docx',
        'doc',
        'txt',
        'mp4',
        'mp3',
        'wav',
        'mkv',
        'avi',
        'mov',
        'flv',
        'wmv',
        'zip',
        'rar',
        '7z',
        'tar',
        'gz',
        'bz2',
        'xz',
        'iso',
        'xml',
        'json',
        'csv',
        'xls',
        'xlsx',
        'ppt',
        'pptx',
        'odt',
        'ods',
        'odp',
        'odg',
        'odf',
        'odc',
        'odm',
        'odf',
        'odt',
        'odp',
        'odg',
      ],
    }),
  })
)
